# Generated by Django 3.2.3 on 2021-05-17 17:10

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('time', models.TimeField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(blank=True, default=None, upload_to=siteapp.models.file_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=siteapp.models.file_path),
        ),
    ]
