# Generated by Django 3.2.3 on 2021-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_message_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='message',
            field=models.ManyToManyField(to='siteapp.Message'),
        ),
    ]
