# Generated by Django 3.2.3 on 2021-06-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_auto_20210617_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type_new',
        ),
        migrations.AddField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('main', 'новина'), ('achive', 'досягнення')], default='', max_length=50),
        ),
    ]
